#pragma once

#include <vector>
#include <string>
#include "general_types.h"
#include "json.hpp"

namespace scheduling_problem
{
    /**
     * @brief Stores information about a single task in schedule
     *
     * Represents a job (task) as an element of the schedule.
     * Job has id (its node number in graph),
     * volume (node weight) and release (the resource released by this job).
     */
    struct Job
    {
        /**
         * Graph node number for the job (task)
         */
        size_t id;
        /**
         * Amount of resource used by the job (task)
         */
        weight_t volume;
        /**
         * Amount of resource released by the job (task) upon completion. Depends on the position of the task in the schedule.
         */
        weight_t release;

        /**
         * Constructor
         */
        Job() = default;

        /**
         * Constructor
         * @param id Node number in Graph
         * @param volume Node weight in Graph
         * @param release The amount of resource released by the job (task)
         */
        Job(size_t id,
            weight_t volume,
            weight_t release)
            : id(id), volume(volume), release(release)
        {
        }
    };

    /**
     * @brief Keeps the partial or complete schedule
     *
     * Schedule is an object generated by each scheduling algorithm. %Schedule consists of
     * jobs (tasks) arranged in the order of execution. To get
     * job in position j, call 'operator []' with j as the argument.
     * %Schedule also has its own json representation and corresponding methods
     * (load, dump) for reading and writing it.
     */
    class Schedule : public std::vector<Job>
    {
    protected:
        weight_t cost_, target_; // peak usage and current usage
        std::string name_;       // schedule name (use there dag name)

    public:
        /**
         * @param size Number of nodes in graph; this class supports predefined schedule size
         * @param name Name of graph; use this for dump schedule in json
         */
        Schedule(size_t size = 0, const std::string &name = "dag");

        /**
         * @param other Schedule to copy from
         */
        Schedule(const Schedule &other);

        /**
         * @param other Schedule to copy from
         */
        Schedule(Schedule &&other) noexcept;

        /**
         * @param recompute Set to True in order to recalculate
         * the goal function of the schedule using cached data. If the value
         * is false then pre-computed goal function value is returned.
         * @return %Schedule cost
         */
        weight_t cost(bool recompute);

        /**
         * @param graph Input graph
         * @return %Schedule cost
         */
        weight_t cost(const Graph &graph);

        /**
         * @return %Schedule cost
         */
        weight_t cost() const;

        /**
         * @param id Number of task's node in the graph
         * @param volume Amount of resource used by the task
         * @param release Amount of resource released by the task
         */
        void push(size_t id, weight_t volume, weight_t release);

        /**
         * Add a task to the end of the schedule
         * @param graph Input graph
         * @param id Number of task's node in the graph
         */
        void push(const Graph &graph, size_t id);

        /**
         * @param job Task for adding
         */
        void push(const Job &job);

        nlohmann::ordered_json json() const;

        void dump(std::string filename) const;

        /**
         * @return Name of the schedule
         */
        std::string name() const;

        void operator=(const Schedule &other);

        /**
         * @return Constructed schedule
         */
        static Schedule load(std::string filename);

        /**
         * @brief Load schedule from json object
         *
         * @return Constructed schedule
         */
        static Schedule load(nlohmann::ordered_json j);
    };
}
